version: 0.0.{build}
branches:
  only:
  - master
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
nuget:
  project_feed: true 
  disable_publish_on_pr: true
init:
- ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME" }
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
test_script:
- ps: dotnet test Result.Tests\System1Group.Lib.Result.Tests.csproj
after_build:
- ps: dotnet pack Result\System1Group.Lib.Result.csproj
on_success:
- ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { Get-ChildItem -Path .\ -Include *.nupkg -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name } } else { Write-Host "Skip uploading artifacts for non-tag build." }